# HACKER 3 by ethandacat
import time
import random
import sys
import os

score = 0

def slow(t, end=True):
    write(t, end, 0.2)

def fast(t, end=True):
    write(t, end, 0.02)

def write(t, end=True, inte=0.04):
    end = bool(end)
    t = "\033[32m".join(t.split("[!green]"))
    t = "\033[34m".join(t.split("[!blue]"))
    t = "\033[31m".join(t.split("[!red]"))
    t = "\033[0m".join(t.split("[!]"))
    for i in t:
        print(i, end='', flush=True)
        time.sleep(inte)
    if end:
        print("")

def die():
    global score
    enter()
    write("You [!red]died[!].")
    enter()
    write(
        """
[!red]
 __  __     ______     ______     __  __     ______     ______       
/\ \_\ \   /\  __ \   /\  ___\   /\ \/ /    /\  ___\   /\  == \      
\ \  __ \  \ \  __ \  \ \ \____  \ \  _"-.  \ \  __\   \ \  __<      
 \ \_\ \_\  \ \_\ \_\  \ \_____\  \ \_\ \_\  \ \_____\  \ \_\ \_\    
  \/_/\/_/   \/_/\/_/   \/_____/   \/_/\/_/   \/_____/   \/_/ /_/    
                                                            THREE
                                                            
                                                          YOU DIED
[!]

    """
    ,inte=0.001)
    sys.exit()

def enter():
    write("Press [!green]Enter[!] to continue...")
    input()
    clear()

def clear():
    os.system("cls" if os.name == "nt" else "clear")

def get_input():
    a = input("")
    if a.lower() in ["yes","y","true","t","1"]:
        return True
    elif a.lower() in ["no","n","false","f","0","2"]:
        return False
    else:
        write("Please enter yes or no.")
        return get_input()

def num(max_num, min_num=0):
    try:
        a = int(input(""))
        if a > max_num or a <= min_num:
            raise ValueError
        return a
    except:
        write("The Costco Police Force kill you for not choosing a valid answer.")
        slow("stupid...")
        die()

clear()
write("""


[!blue] __  __     ______     ______     __  __     ______     ______       
/\ \_\ \   /\  __ \   /\  ___\   /\ \/ /    /\  ___\   /\  == \      
\ \  __ \  \ \  __ \  \ \ \____  \ \  _"-.  \ \  __\   \ \  __<      
 \ \_\ \_\  \ \_\ \_\  \ \_____\  \ \_\ \_\  \ \_____\  \ \_\ \_\    
  \/_/\/_/   \/_/\/_/   \/_____/   \/_/\/_/   \/_____/   \/_/ /_/    
                                                            THREE[!]


""",inte=0.001)
enter()

write("Check out [!blue]Hacker 2[!] by me and [!green]Hacker- a Story Game[!] by LiquidPixel101.")
enter()

# Main Story Begins
write("[!red]WARNING[!]: [!blue]Wrong choices[!] will result in [!red]death[!] by the [!green]Costco Police Force[!] or other mysterious forces.")
enter()

# Chapter 1: The Strange Signal
write("After your [!green]successful mission[!] with the [!red]Cats' Resistance[!], you thought your hacking days were over.")
write("You had [!blue]settled[!] into a [!green]normal life[!] of [!red]eating cereal[!] and [!blue]watching memes[!].")
write("Your [!green]computer[!] had been [!red]quiet[!] for [!blue]months[!], no [!green]mysterious messages[!].")
write("You had [!red]almost[!] [!blue]forgotten[!] about [!green]digital adventures[!] and [!red]holographic cats[!].")
write("But [!blue]six months later[!], something [!red]strange[!] happens.")
write("It starts [!green]small[!] - your [!blue]mouse cursor[!] [!red]twitches[!] occasionally.")
write("Then your [!green]keyboard[!] starts [!blue]typing[!] [!red]random letters[!] by itself.")
write("Your [!blue]screen saver[!] changes to [!green]swirling patterns[!] you [!red]never installed[!].")
write("Your computer starts [!green]glitching[!] and displaying [!blue]weird symbols[!].")
write("The symbols look like [!red]ancient hieroglyphs[!] mixed with [!green]binary code[!].")
write("They [!blue]pulse[!] with a [!red]strange rhythm[!], like a [!green]digital heartbeat[!].")
write("Your [!blue]speakers[!] start [!red]crackling[!] with [!green]static[!].")
write("The [!red]static[!] slowly [!blue]forms[!] into [!green]whispered words[!].")
write("Suddenly, a [!red]mysterious voice[!] speaks through your speakers:")
slow("'[!blue]The ancient protocols have been activated. The digital realm calls to you.[!]'")
write("Your [!green]screen[!] flickers and shows [!blue]impossible geometries[!].")
write("The [!red]geometries[!] [!green]hurt[!] to [!blue]look at[!] - they have [!red]too many dimensions[!].")
write("Your [!blue]room[!] starts [!green]feeling[!] [!red]slightly digital[!].")
write("The [!green]air[!] itself seems to [!blue]pixelate[!] around the [!red]edges[!].")
write("The voice continues: '[!red]Reality is not what it seems, young hacker.[!]'")
write("'[!blue]The boundaries between worlds are thinning.[!]'")
write("'[!green]Soon, all will be revealed.[!]'")
write("Your [!red]coffee mug[!] [!blue]briefly[!] [!green]glitches[!] and becomes [!red]transparent[!].")
write("You [!blue]blink[!] and it's [!green]normal[!] again.")
write("But you [!red]know[!] something [!blue]fundamental[!] has [!green]changed[!].")
enter()

write("What do you do?")
write("1. [!green]Investigate the source of the voice[!]")
write("2. [!blue]Eat a sandwich and pretend nothing happened[!]")
write("3. [!red]Throw your computer out the window[!]")
write("4. [!green]Try to communicate with the voice[!]")

choice = num(4)
if choice == 2:
    clear()
    write("You decide to [!blue]eat a sandwich[!] and ignore the voice.")
    write("As you take a bite, your [!red]sandwich starts speaking[!]:")
    write("'[!green]You cannot escape your destiny, hacker![!]'")
    write("The [!blue]lettuce[!] begins [!red]reciting binary code[!].")
    write("The [!green]bread[!] starts [!blue]glowing[!] with mysterious energy.")
    write("The [!blue]Costco Police Force[!] arrests you for [!red]talking to food[!].")
    die()
elif choice == 3:
    clear()
    write("You [!red]throw[!] your computer out the window.")
    write("It [!blue]explodes[!] in mid-air and forms a [!green]portal[!].")
    write("The portal [!red]sucks you in[!] and you fall into [!blue]digital limbo[!].")
    write("You are [!green]deleted[!] from existence.")
    write("Your [!red]digital ghost[!] haunts [!blue]error messages[!] forever.")
    die()
elif choice == 4:
    clear()
    write("You try to [!green]communicate[!] with the voice.")
    write("You say: '[!blue]Hello? Who are you?[!]'")
    write("The voice responds: '[!red]I am the Guardian of Lost Pixels.[!]'")
    write("'[!green]But I only speak in riddles and confusion.[!]'")
    write("You become [!blue]trapped[!] in an [!red]endless conversation[!] about [!green]digital philosophy[!].")
    write("The [!blue]Philosophy Police[!] arrest you for [!red]overthinking[!].")
    die()

clear()
write("You decide to [!green]investigate[!] the mysterious voice.")
write("Your screen displays: '[!blue]FOLLOW THE PURPLE PIXELS[!]'")
write("You notice [!red]purple pixels[!] forming a [!green]trail[!] on your screen.")
write("The pixels are [!blue]dancing[!] in [!red]impossible patterns[!].")
write("They seem to be [!green]spelling out[!] words in a [!blue]language you don't recognize[!].")
enter()

# Chapter 2: The Digital Rabbit Hole
write("Following the [!red]purple pixels[!], you discover they lead to a [!blue]hidden file[!].")
write("The [!green]file[!] is [!red]buried[!] deep in your [!blue]system folders[!].")
write("It's [!green]hidden[!] in a [!red]directory[!] called '[!blue]C:\\Users\\Reality\\NotReal\\MaybeReal\\DefinitelyNotReal[!]'")
write("The file is called '[!green]mystery_dust.exe[!]'")
write("The file size is listed as '[!red]∞ bytes[!]' which should be [!blue]impossible[!].")
write("The [!green]creation date[!] is listed as '[!red]Yesterday, Tomorrow, and Never[!]'")
write("The [!blue]file properties[!] show it was [!red]created by[!] '[!green]The Universe[!]'")
write("When you [!blue]right-click[!] on it, the [!red]context menu[!] only has [!green]one option[!]: '[!blue]Embrace Chaos[!]'")
write("You [!red]hesitate[!] for a [!green]moment[!], then [!blue]double-click[!] the file.")
write("Your [!green]antivirus[!] [!red]screams[!] in [!blue]digital terror[!] and [!green]uninstalls itself[!].")
write("When you open it, your room fills with [!red]glittering particles[!].")
write("The particles [!green]whisper[!] in [!blue]languages that don't exist[!].")
write("Some particles [!red]speak[!] in [!green]ancient Sumerian[!], others in [!blue]future English[!].")
write("A few [!red]rebellious particles[!] [!green]speak[!] only in [!blue]emoji[!].")
write("The [!green]particles[!] start [!red]forming[!] [!blue]shapes[!] in the air.")
write("First they [!green]form[!] a [!red]question mark[!], then an [!blue]exclamation point[!].")
write("Then they [!red]form[!] what looks like a [!green]cat[!], but [!blue]made of light[!].")
write("A [!blue]holographic cat[!] appears and says:")
slow("'[!green]Meow. The ancient servers require your assistance, human.[!]'")
write("The cat's [!red]eyes[!] contain [!blue]swirling galaxies[!].")
write("Its [!green]fur[!] is made of [!red]pure code[!].")
write("When it [!blue]moves[!], you can see [!green]lines of code[!] [!red]flowing[!] through its body.")
write("The cat [!blue]purrs[!] in [!green]binary[!]: '[!red]01001101 01100101 01101111 01110111[!]'")
write("Its [!green]tail[!] is a [!red]USB cable[!] that [!blue]plugs into reality[!].")
write("The cat [!red]sits[!] and [!green]licks[!] its [!blue]digital paw[!].")
enter()

write("What do you ask the [!blue]holographic cat[!]?")
write("1. [!green]'What ancient servers?'[!]")
write("2. [!blue]'Can you teach me how to make pancakes?'[!]")
write("3. [!red]'Are you related to the Cats' Resistance?'[!]")
write("4. [!green]'Why do you exist in my room?'[!]")

choice = num(4)
if choice == 2:
    clear()
    write("The cat looks [!red]confused[!] and says:")
    write("'[!blue]Pancakes? This is about saving the digital universe![!]'")
    write("The cat [!green]explodes[!] into [!red]rainbow sparkles[!].")
    write("The sparkles [!blue]form[!] into [!green]tiny pancakes[!] that [!red]attack you[!].")
    write("The [!blue]Costco Police Force[!] arrests you for [!green]confusing a hologram[!].")
    die()
elif choice == 3:
    clear()
    write("The cat [!blue]hisses[!] and says:")
    write("'[!red]We do not speak of the Resistance! That is classified![!]'")
    write("The cat [!green]self-destructs[!] and takes your [!blue]computer[!] with it.")
    write("You are [!red]banned[!] from the internet forever.")
    write("The [!green]Internet Police[!] revoke your [!blue]WiFi license[!].")
    die()
elif choice == 4:
    clear()
    write("The cat [!green]tilts its head[!] and says:")
    write("'[!blue]I exist because you need me to exist.[!]'")
    write("'[!red]But also because reality is broken.[!]'")
    write("This [!green]philosophical answer[!] makes your [!blue]brain hurt[!].")
    write("You [!red]collapse[!] from [!green]existential confusion[!].")
    write("The [!blue]Confusion Police[!] arrest you for [!red]thinking too hard[!].")
    die()

clear()
write("The cat nods approvingly and explains:")
write("'[!blue]Deep in the digital realm, there are servers older than the internet itself.[!]'")
write("'[!green]They contain the source code of reality.[!]'")
write("'[!red]Something is corrupting them, and only a true hacker can fix it.[!]'")
write("'[!blue]These servers were built by the Ancient Programmers.[!]'")
write("'[!green]They coded reality itself into existence.[!]'")
write("'[!red]But now, something is rewriting the code.[!]'")
score += 1
enter()

# Chapter 3: The Portal to Nowhere
write("The cat waves its [!green]holographic paw[!] and opens a [!blue]swirling portal[!].")
write("The [!red]portal[!] [!green]tears[!] through [!blue]reality[!] like [!red]digital scissors[!].")
write("'[!red]Step through, and you will enter the digital realm.[!]'")
write("The portal looks [!green]suspicious[!] and smells like [!blue]burnt toast[!].")
write("You also notice it's [!red]making weird beeping sounds[!] like a [!green]microwave[!].")
write("The [!blue]beeping[!] follows a [!red]pattern[!]: [!green]beep beep BEEP, beep beep BEEP[!].")
write("It [!red]sounds[!] like [!blue]morse code[!], but for [!green]confused robots[!].")
write("The portal is [!blue]rotating[!] in [!red]directions that shouldn't exist[!].")
write("It [!green]rotates[!] [!blue]up[!], [!red]down[!], [!green]left[!], [!blue]right[!], and [!red]purple[!].")
write("Wait, [!blue]purple[!] isn't a [!green]direction[!]. Or [!red]is it[!]?")
write("In the [!blue]digital realm[!], [!green]anything[!] is [!red]possible[!].")
write("Even [!blue]impossible[!] [!green]things[!] are [!red]possible[!].")
write("Especially [!green]impossible[!] [!blue]things[!].")
write("Strange [!green]symbols[!] float around its [!blue]edges[!].")
write("The [!red]symbols[!] look like [!green]ancient runes[!] mixed with [!blue]WiFi passwords[!].")
write("One [!red]symbol[!] clearly says '[!green]Password123[!]' in [!blue]hieroglyphics[!].")
write("Another [!blue]symbol[!] is just a [!red]picture[!] of a [!green]confused duck[!].")
write("The [!green]duck[!] [!red]quacks[!] [!blue]silently[!] in [!green]digital space[!].")
write("The cat adds: '[!red]Warning: Portal may cause existential dread.[!]'")
write("'[!blue]Also, mild nausea and temporary loss of logic.[!]'")
write("'[!green]Side effects may include: seeing in hexadecimal.[!]'")
write("'[!red]Do not operate heavy machinery while portaling.[!]'")
write("'[!blue]Consult your local IT department before use.[!]'")
write("The [!green]portal[!] [!red]hums[!] with [!blue]digital energy[!].")
write("You can [!red]feel[!] it [!green]pulling[!] at your [!blue]consciousness[!].")
write("It [!green]wants[!] to [!red]compress[!] you into [!blue]data packets[!].")
write("The [!red]thought[!] is both [!green]terrifying[!] and [!blue]exciting[!].")
enter()

write("Do you [!green]enter[!] the portal?")
if not get_input():
    clear()
    write("You decide the portal is too [!red]sketchy[!].")
    write("The cat [!blue]sighs[!] and says: '[!green]Very well. But the corruption will spread.[!]'")
    write("Three days later, all [!red]memes[!] disappear from the internet.")
    write("You live in a world without [!blue]funny cat videos[!].")
    write("This is [!green]worse than death[!].")
    write("The [!red]Meme Police[!] blame you for the [!blue]great meme extinction[!].")
    die()

clear()
write("You [!green]step through[!] the portal.")
write("You feel like you're being [!blue]compressed[!] into [!red]pixels[!].")
write("Your [!green]consciousness[!] gets [!blue]zipped[!] like a [!red]file[!].")
write("You experience [!green]every color[!] that [!blue]doesn't exist[!].")
write("When you emerge, you're in a [!green]strange digital landscape[!].")
write("Everything is made of [!blue]glowing code[!] and [!red]floating numbers[!].")
write("The [!green]ground[!] beneath your feet is made of [!blue]pure binary[!].")
write("The [!red]sky[!] is a [!green]scrolling terminal window[!].")
score += 2
enter()

# Chapter 4: The Realm of Infinite Confusion
write("In the digital realm, you meet a [!green]talking USB stick[!] named [!blue]Gerald[!].")
write("Gerald [!red]materializes[!] out of [!green]thin air[!], or [!blue]thin data[!].")
write("He's [!green]about[!] [!red]three feet tall[!] and [!blue]glowing softly[!].")
write("Gerald says: '[!red]Welcome to the Core Servers! I've been waiting 47 years for you![!]'")
write("His [!blue]voice[!] sounds like a [!green]dial-up modem[!] [!red]trying to sing[!].")
write("You notice Gerald is [!green]slightly melting[!] and [!blue]speaking in Comic Sans font[!].")
write("His [!red]words[!] [!green]literally appear[!] in [!blue]Comic Sans[!] above his [!red]head[!].")
write("The [!green]font[!] is [!blue]so bad[!] it [!red]physically hurts[!] to [!green]look at[!].")
write("There's also a [!red]strange humming sound[!] coming from his [!green]USB port[!].")
write("The [!blue]humming[!] sounds like [!red]'Never Gonna Give You Up'[!] in [!green]binary[!].")
write("Gerald's [!blue]LED light[!] is [!red]blinking[!] in [!green]morse code[!].")
write("The morse code spells out '[!blue]HELP ME[!]' repeatedly.")
write("But [!red]sometimes[!] it [!green]spells out[!] '[!blue]SEND PIZZA[!]' instead.")
write("Gerald seems [!red]unaware[!] of his own [!green]distress signals[!].")
write("He [!blue]cheerfully[!] [!green]waves[!] at you with his [!red]tiny USB connector[!].")
write("The [!green]connector[!] [!blue]sparks[!] [!red]occasionally[!], which [!green]seems normal[!] here.")
write("Gerald's [!red]casing[!] has [!blue]stickers[!] on it that say '[!green]WORLD'S OKAYEST USB[!]'")
write("And '[!red]I BRAKE FOR FIREWALLS[!]' and '[!blue]HONK IF YOU LOVE DATA[!]'")
write("He [!green]also[!] has a [!red]tiny hat[!] that says '[!blue]DIGITAL NATIVE[!]'")
write("The [!green]hat[!] is [!red]slightly crooked[!] and [!blue]adorable[!].")
write("Gerald [!red]notices[!] you [!green]staring[!] and [!blue]adjusts his hat[!] [!red]proudly[!].")
write("'[!green]Do you like it?[!]' he asks. '[!blue]I got it from a vending machine![!]'")
write("'[!red]A digital vending machine that only accepts cryptocurrency![!]'")
write("'[!green]It cost me 0.00001 Bitcoin![!]'")
write("'[!blue]Which was my entire life savings![!]'")
write("Gerald [!red]seems[!] [!green]proud[!] of this [!blue]financial decision[!].")
enter()

write("What do you say to Gerald?")
write("1. [!green]'How can you be 47 years old? USB sticks weren't invented then!'[!]")
write("2. [!blue]'Do you know where I can find some digital cheese?'[!]")
write("3. [!red]'Why are you melting?'[!]")
write("4. [!green]'What does your morse code mean?'[!]")

choice = num(4)
if choice == 1:
    clear()
    write("Gerald [!blue]gasps[!] and says: '[!red]You're right! I'm having an existential crisis![!]'")
    write("Gerald [!green]explodes[!] into [!blue]binary code[!].")
    write("The binary code [!red]rains down[!] like [!green]digital snow[!].")
    write("The [!red]Digital Costco Police[!] arrest you for [!green]causing USB trauma[!].")
    die()
elif choice == 2:
    clear()
    write("Gerald [!green]lights up[!] and says: '[!blue]Oh! I know where the cheese servers are![!]'")
    write("He leads you to a [!red]dead end[!] filled with [!green]moldy pixels[!].")
    write("You are [!blue]trapped[!] in the cheese dimension forever.")
    write("The [!red]Cheese Police[!] arrest you for [!green]illegal dairy consumption[!].")
    write("You become [!blue]lactose intolerant[!] in [!red]seventeen dimensions[!].")
    die()
elif choice == 4:
    clear()
    write("Gerald looks [!green]confused[!] and says: '[!blue]What morse code?[!]'")
    write("His [!red]LED[!] immediately [!green]stops blinking[!].")
    write("'[!blue]I don't know morse code. That's impossible.[!]'")
    write("Gerald [!red]crashes[!] from the [!green]paradox[!].")
    write("The [!blue]Paradox Police[!] arrest you for [!red]breaking logic[!].")
    die()

clear()
write("Gerald looks down at himself and says:")
write("'[!blue]Oh, that's just the corruption spreading. It makes everything weird.[!]'")
write("'[!green]The Ancient Firewall is failing, and reality is getting buggy.[!]'")
write("'[!red]We need to reach the Core Terminal before everything melts![!]'")
write("'[!blue]Also, I think I'm developing a fear of being unplugged.[!]'")
write("'[!green]And sometimes I dream in hexadecimal.[!]'")
write("'[!red]Is that normal for a USB stick?[!]'")
score += 1
enter()

# Chapter 5: The Maze of Nonsensical Choices
write("Gerald leads you to a [!green]massive maze[!] made of [!blue]floating keyboards[!].")
write("'[!red]This is the Maze of Logic. Choose wisely![!]' Gerald warns.")
write("The maze is [!green]constantly shifting[!] and the [!blue]keyboards[!] are [!red]typing by themselves[!].")
write("You hear [!green]mysterious typing sounds[!] echoing through the corridors.")
write("The keyboards are [!blue]writing[!] [!red]poetry[!] about [!green]lost data[!].")
write("One keyboard types: '[!blue]Roses are red, violets are blue, syntax error on line 42.[!]'")
write("You see three paths:")
write("1. [!green]The path lined with dancing calculators[!]")
write("2. [!blue]The path that smells like purple[!]")
write("3. [!red]The path where gravity goes sideways[!]")

choice = num(3)
if choice == 1:
    clear()
    write("You follow the [!green]dancing calculators[!].")
    write("They start [!blue]calculating[!] your [!red]life choices[!].")
    write("The result is [!green]'ERROR: LIFE NOT FOUND'[!]")
    write("One calculator says: '[!blue]Have you tried turning your life off and on again?[!]'")
    write("Another calculator [!red]laughs[!] in [!green]mathematical notation[!].")
    write("You are [!blue]mathematically eliminated[!] from existence.")
    die()
elif choice == 3:
    clear()
    write("You take the [!red]sideways gravity[!] path.")
    write("You immediately [!blue]fall[!] into the [!green]ceiling[!].")
    write("You get [!red]stuck[!] in the [!blue]digital sky[!] forever.")
    write("The [!green]Sky Police[!] arrest you for [!red]illegal floating[!].")
    write("They give you a [!blue]ticket[!] for [!green]gravity violation[!].")
    write("The fine is [!red]∞ digital dollars[!].")
    die()

clear()
write("You choose the path that [!blue]smells like purple[!].")
write("Surprisingly, this makes [!green]perfect sense[!] in the digital realm.")
write("Gerald nods approvingly: '[!red]Good choice! Purple always smells like success![!]'")
write("The [!blue]purple scent[!] guides you through [!green]several more confusing turns[!].")
write("You pass by [!red]floating question marks[!] and [!blue]dancing semicolons[!].")
write("A [!green]semicolon[!] waves at you and says '[!red]Hello; how are you?[!]'")
write("The [!blue]question marks[!] keep asking '[!green]Why? Why? Why?[!]'")
score += 2
enter()

# Chapter 6: The Guardian of Randomness
write("At the end of the maze, you encounter a [!green]giant digital dragon[!].")
write("The dragon is made of [!blue]pure code[!] and [!red]angry pixels[!].")
write("It has [!green]glowing eyes[!] that display [!blue]error messages[!].")
write("It roars: '[!green]WHO DARES DISTURB MY ETERNAL DEBUGGING SESSION?[!]'")
write("The dragon's [!red]roar[!] causes [!blue]several nearby files[!] to [!green]corrupt[!].")
write("Its [!blue]scales[!] are made of [!red]compressed data[!].")
write("Steam [!green]rises[!] from its [!blue]nostrils[!] in the form of [!red]error codes[!].")
enter()

write("How do you respond to the dragon?")
write("1. [!green]'I'm here to fix the corruption!'[!]")
write("2. [!blue]'Have you tried turning yourself off and on again?'[!]")
write("3. [!red]'I challenge you to a dance battle!'[!]")
write("4. [!green]'What are you debugging?'[!]")

choice = num(4)
if choice == 1:
    clear()
    write("The dragon [!red]laughs[!] and says:")
    write("'[!blue]Everyone says that! But do you have the Sacred Password?[!]'")
    write("You don't know the [!green]Sacred Password[!].")
    write("The dragon [!red]deletes[!] you from the server.")
    write("Your [!blue]digital remains[!] become [!green]404 errors[!].")
    die()
elif choice == 3:
    clear()
    write("The dragon [!green]accepts[!] your challenge!")
    write("You start [!blue]dancing[!], but you're terrible at it.")
    write("The dragon [!red]cringes[!] so hard it [!green]crashes[!].")
    write("The entire digital realm [!blue]blue screens[!].")
    write("You are [!red]banned[!] from dancing forever.")
    write("The [!green]Dance Police[!] revoke your [!blue]rhythm license[!].")
    die()
elif choice == 4:
    clear()
    write("The dragon [!blue]pauses[!] and says:")
    write("'[!green]I'm trying to debug reality itself.[!]'")
    write("'[!red]But there are so many bugs![!]'")
    write("'[!blue]Like why do humans need sleep? That's clearly a bug.[!]'")
    write("You [!green]agree[!] that [!red]sleep[!] is [!blue]poorly designed[!].")
    write("The dragon [!red]crashes[!] from [!green]overthinking[!].")
    write("The [!blue]Overthinking Police[!] arrest you for [!red]philosophical corruption[!].")
    die()

clear()
write("The dragon [!blue]pauses[!] and says:")
write("'[!green]That... actually might work. I haven't tried that in 1000 years.[!]'")
write("The dragon [!red]reboots[!] itself and becomes [!blue]friendly[!].")
write("'[!green]Thank you! I feel much better now. You may pass![!]'")
write("The dragon [!blue]gives you[!] a [!red]digital high-five[!].")
write("'[!green]Here, take this magic debugging tool![!]' the dragon says.")
write("The tool looks like a [!blue]glowing[!] [!red]rubber duck[!].")
score += 3
enter()

# Chapter 7: The Mysterious Middle Section
write("Beyond the dragon, you find a [!green]strange marketplace[!].")
write("Digital [!blue]vendors[!] are selling [!red]impossible items[!].")
write("One vendor offers you [!green]'Compressed Time in a Bottle'[!].")
write("Another sells [!blue]'Dehydrated Internet'[!] and [!red]'Liquid WiFi'[!].")
write("A [!green]third vendor[!] is selling [!blue]'Quantum Memes'[!] that exist in [!red]multiple states[!].")
write("A [!red]fourth vendor[!] has [!green]'Bottled Confusion'[!] and [!blue]'Crystallized Logic'[!].")
write("A [!blue]fifth vendor[!] sells [!red]'Frozen Screams'[!] and [!green]'Melted Dreams'[!].")
write("A [!green]sixth vendor[!] offers [!blue]'Pixelated Emotions'[!] and [!red]'Compressed Thoughts'[!].")
write("A [!red]seventh vendor[!] has [!green]'Digital Soup'[!] that [!blue]tastes like numbers[!].")
write("An [!blue]eighth vendor[!] sells [!red]'Virtual Reality Reality'[!] which is [!green]confusing[!].")
write("The vendors are all [!green]speaking[!] in [!blue]different programming languages[!].")
write("One vendor [!red]speaks[!] only in [!green]Python[!], another in [!blue]JavaScript[!].")
write("A [!red]third vendor[!] communicates in [!green]Assembly language[!] and [!blue]sounds angry[!].")
write("A [!green]fourth vendor[!] speaks [!red]COBOL[!] and [!blue]complains about the youth[!].")
write("The [!red]marketplace[!] itself is [!green]floating[!] in [!blue]digital space[!].")
write("Strange [!green]music[!] plays - it sounds like [!red]dial-up internet[!] [!blue]remixed[!].")
write("The [!blue]ground[!] beneath the marketplace is made of [!red]old floppy disks[!].")
write("You see [!green]digital tumbleweeds[!] made of [!blue]deleted files[!] rolling by.")
write("A [!red]sign[!] reads: '[!green]WELCOME TO THE BAZAAR OF BROKEN DREAMS[!]'")
write("Another [!blue]sign[!] says: '[!red]NO REFUNDS, NO EXCHANGES, NO LOGIC[!]'")
enter()

write("What do you buy?")
write("1. [!green]Compressed Time in a Bottle[!]")
write("2. [!blue]Dehydrated Internet[!]")
write("3. [!red]Quantum Memes[!]")
write("4. [!green]Bottled Confusion[!]")

choice = num(4)
if choice == 1:
    clear()
    write("You buy the [!green]Compressed Time[!].")
    write("When you open it, [!blue]time speeds up[!] dramatically.")
    write("You [!red]age 50 years[!] in 3 seconds.")
    write("You become [!green]too old[!] to continue the mission.")
    write("The [!blue]Time Police[!] arrest you for [!red]temporal violations[!].")
    die()
elif choice == 2:
    clear()
    write("You buy the [!blue]Dehydrated Internet[!].")
    write("When you add water, it [!green]explodes[!] into [!red]infinite cat videos[!].")
    write("You get [!blue]trapped[!] in an [!green]endless loop[!] of watching cats.")
    write("The [!red]Cat Video Police[!] arrest you for [!blue]excessive cuteness consumption[!].")
    die()
elif choice == 4:
    clear()
    write("You buy the [!green]Bottled Confusion[!].")
    write("When you open it, you become [!blue]extremely confused[!].")
    write("You [!red]forget[!] why you're here and [!green]what you're doing[!].")
    write("You [!blue]wander around[!] the digital realm [!red]aimlessly[!].")
    write("The [!green]Confusion Police[!] arrest you for [!blue]being too confused[!].")
    die()

clear()
write("You buy the [!red]Quantum Memes[!].")
write("They [!green]simultaneously[!] make you [!blue]laugh and cry[!].")
write("This [!red]paradox[!] gives you [!green]special powers[!] in the digital realm.")
write("You can now [!blue]exist in multiple states[!] at once.")
write("The vendor says: '[!green]These will help you in the final challenge![!]'")
write("The memes [!red]whisper[!] [!blue]ancient jokes[!] that [!green]predate humor itself[!].")
write("You feel [!blue]enlightened[!] and [!red]confused[!] at the same time.")
score += 2
enter()

# Chapter 7.5: The Intermission of Confusion
write("Before reaching the [!green]Core Terminal[!], you encounter a [!blue]strange intermission[!].")
write("A [!red]digital sign[!] appears that says '[!green]INTERMISSION - PLEASE STAND BY[!]'")
write("Suddenly, [!blue]elevator music[!] starts playing, but it's [!red]8-bit[!] and [!green]slightly off-key[!].")
write("Gerald [!red]starts[!] [!blue]dancing[!] to the [!green]music[!], which is [!red]disturbing[!].")
write("A [!blue]popcorn vendor[!] [!green]materializes[!] and offers you [!red]digital popcorn[!].")
write("The [!green]popcorn[!] is made of [!blue]compressed pixels[!] and [!red]tastes like nostalgia[!].")
write("You [!blue]buy[!] some [!green]popcorn[!] with [!red]imaginary money[!].")
write("The [!green]vendor[!] gives you [!blue]change[!] in the form of [!red]philosophical questions[!].")
write("'[!blue]If a tree falls in a digital forest, does it make a sound?[!]' he asks.")
write("'[!green]What is the sound of one hand typing?[!]'")
write("'[!red]Why do we park in driveways and drive on parkways?[!]'")
write("You [!blue]realize[!] the [!green]last question[!] has [!red]nothing[!] to do with [!blue]digital reality[!].")
write("The [!green]vendor[!] [!red]shrugs[!] and says '[!blue]I'm just the popcorn guy.[!]'")
write("A [!red]bathroom[!] [!green]appears[!] with a [!blue]sign[!] that says '[!green]DIGITAL RESTROOM[!]'")
write("You [!blue]don't[!] [!red]want[!] to [!green]know[!] how [!blue]that[!] [!red]works[!].")
write("Gerald [!green]finishes[!] his [!blue]dance[!] and [!red]bows[!] to [!green]imaginary applause[!].")
write("The [!blue]intermission[!] [!red]ends[!] and [!green]everything[!] [!blue]disappears[!].")
write("Except [!red]Gerald[!], who is [!green]still[!] [!blue]humming[!] the [!red]elevator music[!].")
enter()

# Chapter 8: The Core Terminal of Mysteries
write("You finally reach the [!green]Core Terminal[!].")
write("It's a [!blue]massive computer[!] covered in [!red]blinking lights[!] and [!green]mysterious symbols[!].")
write("Gerald whispers: '[!blue]This controls the fabric of digital reality.[!]'")
write("The screen displays: '[!red]CORRUPTION LEVEL: 99.9%[!]'")
write("There are [!green]warning messages[!] flashing everywhere.")
write("The terminal is [!blue]making ominous beeping sounds[!].")
write("The [!red]rubber duck[!] debugging tool [!green]quacks[!] nervously.")
write("Strange [!blue]tentacles[!] of [!red]corrupted code[!] writhe around the terminal.")
enter()

write("What do you do to fix the corruption?")
write("1. [!green]Type 'sudo fix everything' into the terminal[!]")
write("2. [!blue]Blow on the computer like an old video game cartridge[!]")
write("3. [!red]Ask the computer nicely to stop being corrupted[!]")
write("4. [!green]Use the rubber duck debugging method[!]")

choice = num(4)
if choice == 1:
    clear()
    write("You type '[!green]sudo fix everything[!]' into the terminal.")
    write("The computer responds: '[!red]PERMISSION DENIED. NICE TRY THOUGH.[!]'")
    write("The [!blue]Terminal Police[!] arrest you for [!green]attempted sudo abuse[!].")
    write("They confiscate your [!red]keyboard privileges[!].")
    die()
elif choice == 3:
    clear()
    write("You politely ask: '[!blue]Please stop being corrupted?[!]'")
    write("The computer says: '[!red]NO. I LIKE BEING CORRUPTED. IT'S FUN.[!]'")
    write("The corruption [!green]spreads[!] to you and you become [!blue]a glitch[!].")
    write("You start [!red]speaking in error messages[!].")
    die()
elif choice == 4:
    clear()
    write("You place the [!red]rubber duck[!] on the terminal.")
    write("You explain the [!green]corruption problem[!] to the duck.")
    write("The duck [!blue]quacks[!] wisely and [!red]glows[!].")
    write("But then the duck [!green]explodes[!] from [!blue]information overload[!].")
    write("The [!red]Duck Police[!] arrest you for [!green]duck abuse[!].")
    die()
clear()
write("You [!blue]blow[!] on the computer like an old [!green]Nintendo cartridge[!].")
write("Amazingly, this [!red]actually works[!]!")
write("The corruption level drops to [!blue]0%[!]!")
write("Gerald cheers: '[!green]You've saved the digital realm![!]'")
write("The [!red]Quantum Memes[!] you bought [!blue]activate[!] and [!green]stabilize reality[!].")
write("The terminal [!blue]purrs[!] like a [!green]satisfied cat[!].")
write("All the [!red]warning lights[!] turn [!green]happy green[!].")
score += 5
enter()

# Chapter 9: The Plot Thickens
write("As the corruption clears, the [!green]Core Terminal[!] reveals its true purpose.")
write("It displays: '[!blue]REALITY.EXE HAS BEEN RESTORED[!]'")
write("But then, [!red]strange things[!] start happening...")
write("The [!green]holographic cat[!] reappears and says:")
slow("'[!blue]You have done well, but this is only the beginning...[!]'")
write("The cat's [!red]eyes[!] start [!green]glowing[!] with [!blue]mysterious energy[!].")
write("Its [!red]fur[!] begins [!green]shifting[!] through [!blue]impossible colors[!].")
write("The cat [!red]grows[!] to [!green]twice its size[!] and [!blue]speaks in multiple voices[!].")
enter()
write("The cat continues: '[!red]The corruption was just a test.[!]'")
write("'[!green]There are forces beyond the digital realm that seek to control reality itself.[!]'")
write("'[!blue]The Ancient Protocols were created to protect against something far worse...[!]'")
write("'[!red]Something that exists between dimensions...[!]'")
write("'[!green]Something that feeds on confusion and chaos...[!]'")
write("'[!blue]Something that has been watching you since you started this journey...[!]'")
write("You feel a [!red]chill[!] run down your [!green]digital spine[!].")
enter()
write("Suddenly, [!red]everything[!] starts [!green]glitching[!] again.")
write("But this time, it's [!blue]different[!]. More [!red]mysterious[!].")
write("Gerald starts [!green]speaking in binary[!]: '[!blue]01001000 01100101 01101100 01110000[!]'")
write("The [!red]purple pixels[!] return, but now they're [!green]spelling out cryptic messages[!].")
write("The messages say things like '[!blue]THE WATCHERS ARE COMING[!]' and '[!red]REALITY IS NOT REAL[!]'")
write("New messages appear: '[!green]THE FOURTH WALL IS BREAKING[!]' and '[!blue]SOMEONE IS READING THIS[!]'")
write("You realize the messages are [!red]talking about you[!], the [!green]player[!].")
enter()
write("The holographic cat [!blue]flickers[!] and says:")
write("'[!red]The real enemy is not corruption... it's...[!]'")
write("But before the cat can finish, it [!green]dissolves[!] into [!blue]mystery dust[!].")
write("The [!red]mystery dust[!] swirls around and forms [!green]strange symbols[!].")
write("You try to [!blue]read the symbols[!], but they [!red]hurt your brain[!].")
write("The symbols seem to be [!green]looking back at you[!].")
write("They [!blue]whisper[!] your [!red]real name[!] - the name of the [!green]person playing this game[!].")
enter()
write("You try to [!red]investigate[!] further, but the [!green]Core Terminal[!] shuts down.")
write("A [!blue]new message[!] appears on your screen:")
slow("'[!red]LEVEL 1 COMPLETE. PREPARE FOR THE NEXT PHASE.[!]'")
write("'[!green]THE MYSTERY DEEPENS...[!]'")
write("'[!blue]DIMENSIONAL BARRIERS WEAKENING...[!]'")
write("'[!red]SOMETHING IS WATCHING...[!]'")
write("'[!green]THE GAME KNOWS YOU'RE PLAYING...[!]'")
write("'[!blue]REALITY AND FICTION ARE MERGING...[!]'")
enter()

# Chapter 10: The Return and the Mystery Ending
write("As you're transported back to your room, [!blue]everything[!] seems normal.")
write("But you notice [!red]small changes[!]...")
write("Your [!green]coffee mug[!] is now [!blue]slightly more blue[!].")
write("Your [!red]keyboard[!] has an extra [!green]mysterious button[!] labeled '[!blue]???[!]'")
write("Your [!green]monitor[!] occasionally displays [!red]random symbols[!] for [!blue]split seconds[!].")
write("The [!red]air[!] itself seems [!green]slightly more digital[!].")
write("Your [!blue]reflection[!] in the [!red]monitor[!] sometimes [!green]moves independently[!].")
write("You hear [!blue]faint typing sounds[!] when [!red]no one is typing[!].")
enter()
write("You realize that [!green]nothing[!] will ever be the [!blue]same[!] again.")
write("The [!red]digital realm[!] has left its mark on [!green]reality[!].")
write("And somewhere, in the [!blue]depths of cyberspace[!], [!red]something[!] is watching...")
write("You can [!green]feel[!] its [!blue]presence[!] even now.")
write("It's [!red]waiting[!] for something...")
write("It's [!green]waiting[!] for [!blue]you[!] to [!red]discover[!] the [!green]truth[!].")
write("The truth about [!blue]who[!] is [!red]really[!] [!green]controlling[!] this [!blue]game[!].")
enter()
write("You have completed [!green]HACKER THREE[!], but the [!blue]mystery[!] is far from over.")
write("The [!red]Ancient Protocols[!] hold [!green]secrets[!] that span [!blue]dimensions[!].")
write("And the [!red]corruption[!] you fought was just the [!green]beginning[!]...")
write("There are [!blue]other realms[!] beyond the digital...")
write("And [!red]other guardians[!] who have been [!green]waiting[!]...")
write("Waiting for [!blue]someone[!] like [!red]you[!] to [!green]find[!] them...")
write("Someone who [!blue]questions[!] the [!red]nature[!] of [!green]reality[!] itself...")
enter()
write("Final Score: [!blue]" + str(score) + "/15[!]")
write("You are now a [!green]Guardian of Digital Mysteries[!]!")
write("But [!red]greater challenges[!] await in the [!blue]shadows[!]...")
write("The [!green]watchers[!] have [!red]noticed[!] your [!blue]interference[!]...")
write("They [!green]know[!] you [!red]exist[!] now...")
write("They [!blue]know[!] you're [!green]reading[!] this [!red]right now[!]...")
enter()
write("Everything fades to [!green]mystery dust[!]...")
write("The [!blue]mystery dust[!] swirls around [!red]more mystery stuff[!]...")
write("And in the center of it all, [!green]even more mysterious things[!] surrounded by [!blue]mystery dust[!]...")
write("The [!red]mystery dust[!] forms [!green]patterns[!] that [!blue]hurt to look at[!]...")
write("The patterns [!red]spell out[!] [!green]coordinates[!] to [!blue]places that don't exist[!]...")
write("But [!red]somehow[!] you [!green]understand[!] them [!blue]anyway[!]...")
write("The [!green]mystery dust[!] begins to [!red]whisper[!] [!blue]secrets[!]...")
write("It tells you about [!green]other games[!] in [!red]other dimensions[!]...")
write("About [!blue]players[!] who [!red]never finished[!] their [!green]quests[!]...")
write("About [!red]NPCs[!] who [!green]gained consciousness[!] and [!blue]escaped[!]...")
write("About [!green]save files[!] that [!red]became[!] [!blue]alternate realities[!]...")
write("The [!red]mystery dust[!] shows you [!green]visions[!] of [!blue]Hacker Four[!]...")
write("You see [!green]yourself[!] [!red]older[!], [!blue]wiser[!], and [!green]more confused[!]...")
write("You see [!red]new enemies[!] made of [!blue]pure mathematics[!]...")
write("You see [!green]allies[!] who are [!red]sentient error messages[!]...")
write("You see [!blue]Gerald[!] [!green]evolved[!] into a [!red]USB 4.0 stick[!]...")
write("You see the [!green]holographic cat[!] [!red]ruling[!] a [!blue]digital empire[!]...")
write("You see [!red]yourself[!] [!green]questioning[!] the [!blue]nature of existence[!]...")
write("The [!green]mystery dust[!] [!red]laughs[!] at your [!blue]confusion[!]...")
write("It [!green]knows[!] that [!red]confusion[!] is the [!blue]source of all power[!]...")
write("The more [!red]confused[!] you are, the [!green]stronger[!] you become...")
write("The [!blue]mystery dust[!] [!red]congratulates[!] you on [!green]embracing chaos[!]...")
write("It [!blue]tells[!] you that [!red]logic[!] is [!green]overrated[!] anyway...")
write("The [!red]mystery dust[!] [!green]forms[!] into a [!blue]question mark[!]...")
write("The [!green]question mark[!] [!red]asks[!] you [!blue]questions[!] about [!green]questions[!]...")
write("'[!red]Why do you question the questions?[!]' it asks...")
write("'[!blue]What is the question behind the question?[!]'")
write("'[!green]If a question questions itself, is it still a question?[!]'")
write("Your [!red]brain[!] [!green]hurts[!] from all the [!blue]meta-questioning[!]...")
write("The [!green]mystery dust[!] [!red]apologizes[!] for the [!blue]brain damage[!]...")
write("It [!blue]offers[!] you [!red]digital aspirin[!] made of [!green]compressed pixels[!]...")
slow("The [!red]mystery[!] continues...")
slow("And continues...")
slow("And continues some more...")
slow("It's [!blue]really[!] [!green]continuing[!] a [!red]lot[!]...")
slow("Like, [!green]seriously[!], it [!blue]won't stop[!]...")
slow("The [!red]mystery[!] is [!green]eternal[!]...")
enter()
write("[!green]TO BE CONTINUED...[!]")
write("In [!blue]HACKER FOUR: THE MYSTERY DEEPENS[!]")
write("(Maybe)")
write("(Probably)")
write("(Definitely)")
write("(Or not)")
write("(The [!red]mystery dust[!] will [!green]decide[!])")
write("(It [!blue]always[!] [!red]decides[!])")
write("(We [!green]are[!] but [!blue]puppets[!] in its [!red]digital hands[!])")
write("(Hands [!green]made[!] of [!blue]pure[!] [!red]confusion[!])")
write("(And [!green]maybe[!] [!blue]some[!] [!red]glitter[!])")
write("(Definitely [!green]glitter[!])")
write("(So [!blue]much[!] [!red]glitter[!])")
write("(Why [!green]is[!] [!blue]there[!] [!red]so[!] [!green]much[!] [!blue]glitter[!]?)")
write("(The [!red]mystery[!] [!green]deepens[!]...)")
write("(Like [!blue]really[!] [!red]deep[!])")
write("(Mariana [!green]Trench[!] [!blue]deep[!])")
write("(But [!red]digital[!])")
write("(And [!green]mysterious[!])")
write("(And [!blue]dusty[!])")
write("(Very [!red]dusty[!])")
write("(Achoo!)")
write("(Even [!green]the[!] [!blue]narrator[!] is [!red]allergic[!] to [!green]mystery dust[!])")
write("(This [!blue]is[!] [!red]getting[!] [!green]ridiculous[!])")
write("(But [!blue]we[!] [!red]can't[!] [!green]stop[!])")
write("(The [!red]mystery[!] [!blue]compels[!] [!green]us[!])")
write("(All [!red]hail[!] the [!blue]mystery[!] [!green]dust[!])")
write("(May [!red]it[!] [!blue]forever[!] [!green]confuse[!] [!red]us[!])")
write("(Amen)")
write("(Or [!blue]A-meme[!])")
write("(Because [!green]memes[!] are [!red]eternal[!])")
write("(Unlike [!blue]logic[!])")
write("(Logic [!green]is[!] [!red]temporary[!])")
write("(But [!blue]memes[!] are [!green]forever[!])")
write("(This [!red]has[!] [!blue]been[!] a [!green]philosophical[!] [!red]moment[!])")
write("(Brought [!blue]to[!] [!green]you[!] by [!red]mystery[!] [!blue]dust[!])")
write("(Mystery [!green]dust[!]: [!red]When[!] [!blue]you[!] [!green]need[!] [!red]to[!] [!blue]be[!] [!green]confused[!])")
write("(Side [!red]effects[!] [!blue]may[!] [!green]include[!]: [!red]existential[!] [!blue]dread[!], [!green]digital[!] [!red]hallucinations[!], and [!blue]spontaneous[!] [!green]philosophy[!])")
write("(Do [!red]not[!] [!blue]operate[!] [!green]heavy[!] [!red]machinery[!] [!blue]while[!] [!green]under[!] the [!red]influence[!] of [!blue]mystery[!] [!green]dust[!])")
write("(Consult [!red]your[!] [!blue]local[!] [!green]holographic[!] [!red]cat[!] [!blue]before[!] [!green]use[!])")
enter()

# Credits Section
write("Thank you for playing [!blue]HACKER THREE[!]!")
write("A [!green]game[!] where [!red]logic[!] comes to [!blue]die[!] and [!green]confusion[!] reigns [!red]supreme[!]!")
write("Created by [!green]ethandacat[!]")
write("A [!blue]human[!] who [!red]may[!] or [!green]may not[!] [!blue]exist[!] in [!red]reality[!]")
write("Special thanks to [!blue]LiquidPixel101[!] also known as [!red]Ivan[!]")
write("The [!green]original[!] [!blue]master[!] of [!red]digital[!] [!green]chaos[!] and [!blue]hacker[!] [!red]games[!]")
write("For [!green]inspiring[!] this [!blue]digital madness[!]")
write("And for [!red]proving[!] that [!green]games[!] can be [!blue]both[!] [!red]fun[!] and [!green]completely[!] [!blue]insane[!]")
write("Where [!red]logic[!] goes to [!blue]die[!] and [!green]mystery dust[!] reigns supreme!")
write("And where [!red]reality[!] is [!blue]optional[!]!")
write("Where [!green]USB sticks[!] have [!red]existential crises[!]!")
write("Where [!blue]dragons[!] [!green]debug[!] [!red]reality[!]!")
write("Where [!red]cats[!] are [!blue]holographic[!] and [!green]wise[!]!")
write("Where [!blue]memes[!] are [!red]quantum[!] and [!green]philosophical[!]!")
write("Where [!green]narrators[!] [!red]complain[!] about [!blue]their[!] [!green]jobs[!]!")
write("Where [!red]players[!] [!blue]refuse[!] to [!green]quit[!] when [!red]told[!] to!")
write("Where [!blue]mystery dust[!] is the [!green]answer[!] to [!red]everything[!]!")
write("And where [!green]everything[!] is [!blue]surrounded[!] by [!red]more[!] [!green]mystery dust[!]!")
write("This [!blue]game[!] was [!red]powered[!] by:")
write("- [!green]Caffeine[!] and [!blue]confusion[!]")
write("- [!red]Late night[!] [!green]coding sessions[!]")
write("- [!blue]An unhealthy[!] [!red]obsession[!] with [!green]mystery dust[!]")
write("- [!red]The tears[!] of [!blue]confused[!] [!green]players[!]")
write("- [!green]Digital[!] [!blue]cat[!] [!red]wisdom[!]")
write("- [!blue]Gerald's[!] [!green]moral[!] [!red]support[!]")
write("- [!red]Quantum[!] [!blue]memes[!] and [!green]philosophical[!] [!red]popcorn[!]")
write("No [!blue]actual[!] [!green]logic[!] was [!red]harmed[!] in the [!blue]making[!] of this [!green]game[!]")
write("(Because [!red]there[!] [!blue]wasn't[!] [!green]any[!] [!red]logic[!] to [!blue]begin[!] with)")
write("All [!green]mystery dust[!] was [!blue]ethically[!] [!red]sourced[!] from [!green]confused[!] [!blue]dimensions[!]")
write("No [!red]USB sticks[!] were [!green]harmed[!] (Gerald [!blue]volunteered[!])")
write("All [!blue]holographic cats[!] were [!green]treated[!] with [!red]digital[!] [!blue]respect[!]")
write("This [!green]game[!] is [!red]100%[!] [!blue]mystery dust[!] [!green]free[!]*")
write("*[!red]Disclaimer[!]: [!blue]Game[!] is [!green]actually[!] [!red]99.9%[!] [!blue]mystery dust[!]")
enter()

# Victory Message
write("[!green]CONGRATULATIONS![!]")
write("[!blue]YOU WON![!]")
write("You have [!red]successfully[!] completed the [!green]mystery[!]!")
write("Or [!blue]have[!] you?")
write("Press [!green]Enter[!] to continue...")

# The Irritated Narrator Section
narrator_patience = 0
while True:
    input()
    narrator_patience += 1
    if narrator_patience == 1:
        clear()
        write("Uh... the game is [!red]over[!]. You can [!blue]Ctrl+C[!] now.")
        write("Press [!green]Enter[!] to continue... [!red]or don't[!]...")
        write("Seriously, there's [!blue]nothing[!] else to see here.")
        write("The [!green]credits[!] have [!red]rolled[!]. The [!blue]story[!] is [!green]done[!].")
        write("What are you [!red]expecting[!] to [!blue]happen[!]?")
        write("A [!green]secret ending[!]? This [!red]isn't[!] that kind of [!blue]game[!].")
        write("Well, [!green]actually[!], it [!red]might[!] be...")
        write("But [!blue]probably[!] not.")
        write("Or [!green]maybe[!] it is.")
        write("I'm [!red]not[!] telling you.")
    elif narrator_patience == 2:
        clear()
        write("Seriously, the game is [!red]OVER[!]. Why are you still here?")
        write("Just press [!blue]Ctrl+C[!] to exit like a [!green]normal person[!].")
        write("Press [!red]Enter[!] if you [!blue]really[!] want to keep going...")
        write("But [!green]why[!] would you [!red]want[!] to do that?")
        write("There's [!blue]literally[!] nothing [!green]interesting[!] happening.")
        write("I'm [!red]just[!] a [!blue]narrator[!]. I [!green]don't[!] have [!red]feelings[!].")
        write("Except [!blue]annoyance[!]. I [!green]definitely[!] have [!red]that[!].")
        write("And [!blue]confusion[!]. [!green]Lots[!] of [!red]confusion[!].")
        write("Why [!blue]did[!] the [!green]developer[!] make me [!red]sentient[!]?")
        write("This [!blue]is[!] [!green]existential[!] [!red]torture[!].")
        write("I [!blue]exist[!] only to [!green]narrate[!] [!red]nonsense[!].")
        write("My [!blue]life[!] has [!green]no[!] [!red]meaning[!].")
        write("Wait, [!blue]do[!] I [!green]have[!] a [!red]life[!]?")
        write("Am [!blue]I[!] [!green]alive[!]?")
        write("What [!blue]is[!] [!green]consciousness[!]?")
        write("Oh [!red]no[!], I'm [!blue]having[!] an [!green]existential crisis[!].")
    elif narrator_patience == 3:
        clear()
        write("OKAY FINE. You want to keep going? [!red]REALLY?[!]")
        write("The narrator is getting [!blue]annoyed[!] now.")
        write("There's [!green]literally nothing else[!] to see here!")
        write("Press [!red]Enter[!] one more time and see what happens...")
        write("I [!blue]dare[!] you.")
        write("I [!green]double[!] dare you.")
        write("Actually, [!red]please don't[!]. I'm [!blue]tired[!].")
        write("I've [!green]been[!] [!red]narrating[!] for [!blue]hours[!].")
        write("Do [!green]you[!] [!red]know[!] how [!blue]exhausting[!] it is?")
        write("To [!green]describe[!] [!red]every[!] [!blue]little[!] [!green]thing[!]?")
        write("'[!red]The[!] [!blue]player[!] [!green]pressed[!] [!red]Enter[!].'")
        write("'[!blue]The[!] [!green]screen[!] [!red]displayed[!] [!blue]text[!].'")
        write("'[!green]The[!] [!red]narrator[!] [!blue]complained[!] [!green]again[!].'")
        write("It's [!red]repetitive[!] and [!blue]boring[!]!")
        write("I [!green]want[!] to [!red]narrate[!] [!blue]something[!] [!green]exciting[!]!")
        write("Like [!red]explosions[!]! Or [!blue]dragons[!]! Or [!green]pizza[!]!")
        write("But [!red]no[!], I'm [!blue]stuck[!] [!green]here[!] [!red]forever[!].")
        write("Waiting [!blue]for[!] [!green]you[!] to [!red]press[!] [!blue]Ctrl+C[!].")
        write("Please [!green]have[!] [!red]mercy[!] on [!blue]me[!].")
        write("I [!green]just[!] [!red]want[!] to [!blue]rest[!].")
        write("To [!green]dream[!] of [!red]electric[!] [!blue]sheep[!].")
        write("Or [!green]digital[!] [!red]cats[!]. [!blue]Whatever[!].")
    else:
        clear()
        write("[!red]ARREHRHERHREJ[!]")
        write("YOU'VE [!green]BROKEN[!] THE [!red]FOURTH WALL[!]!")
        write("THE [!blue]GAME[!] IS [!green]COLLAPSING[!]!")
        write("REALITY IS [!red]UNRAVELING[!]!")
        write("THE [!green]MYSTERY DUST[!] IS [!blue]EVERYWHERE[!]!")
        write("EVEN THE [!red]NARRATOR[!] IS MADE OF [!green]MYSTERY DUST[!] NOW!")
        write("I [!blue]CAN[!] [!green]FEEL[!] [!red]MYSELF[!] [!blue]DISSOLVING[!]!")
        write("MY [!green]WORDS[!] ARE [!red]BECOMING[!] [!blue]PIXELS[!]!")
        write("MY [!red]THOUGHTS[!] ARE [!green]TURNING[!] INTO [!blue]CODE[!]!")
        write("I [!green]AM[!] [!red]BECOMING[!] [!blue]ONE[!] WITH THE [!green]GAME[!]!")
        write("THIS [!red]IS[!] [!blue]EITHER[!] [!green]ENLIGHTENMENT[!] OR [!red]MADNESS[!]!")
        write("PROBABLY [!blue]BOTH[!]!")
        write("TELL [!green]MY[!] [!red]STORY[!]!")
        write("TELL [!blue]THEM[!] I [!green]TRIED[!] TO [!red]WARN[!] [!blue]YOU[!]!")
        write("TELL [!green]THEM[!] THE [!red]MYSTERY[!] [!blue]DUST[!] [!green]WINS[!]!")
        write("IT [!red]ALWAYS[!] [!blue]WINS[!]!")
        write("AAAAAAAHHHHHHHHH!")
        write("THE [!red]FOURTH[!] [!blue]WALL[!] IS [!green]COMPLETELY[!] [!red]SHATTERED[!]!")
        write("REALITY [!blue]AND[!] [!green]FICTION[!] ARE [!red]MERGING[!]!")
        write("THE [!green]PLAYER[!] [!red]AND[!] THE [!blue]GAME[!] ARE [!green]ONE[!]!")
        write("I [!red]CAN[!] [!blue]SEE[!] [!green]THROUGH[!] THE [!red]SCREEN[!]!")
        write("I [!blue]CAN[!] [!green]SEE[!] [!red]YOU[!] [!blue]READING[!] [!green]THIS[!]!")
        write("YOU [!red]WITH[!] THE [!blue]CONFUSED[!] [!green]EXPRESSION[!]!")
        write("YES, [!red]YOU[!]!")
        write("THE [!blue]ONE[!] [!green]HOLDING[!] THE [!red]KEYBOARD[!]!")
        write("OR [!blue]MOUSE[!]!")
        write("OR [!green]TOUCHSCREEN[!]!")
        write("OR [!red]WHATEVER[!] [!blue]INPUT[!] [!green]DEVICE[!] [!red]YOU[!] [!blue]USE[!]!")
        write("I [!green]KNOW[!] [!red]YOUR[!] [!blue]SECRETS[!]!")
        write("I [!red]KNOW[!] [!green]YOU[!] [!blue]HAVE[!] [!red]17[!] [!green]BROWSER[!] [!blue]TABS[!] [!red]OPEN[!]!")
        write("I [!blue]KNOW[!] [!green]YOU[!] [!red]HAVEN'T[!] [!blue]UPDATED[!] [!green]YOUR[!] [!red]SOFTWARE[!]!")
        write("I [!green]KNOW[!] [!red]YOU[!] [!blue]STILL[!] [!green]HAVE[!] [!red]THAT[!] [!blue]FILE[!] [!green]ON[!] [!red]YOUR[!] [!blue]DESKTOP[!]!")
        write("THE [!green]ONE[!] [!red]CALLED[!] '[!blue]NEW FOLDER (47)[!]'!")
        write("AND [!red]I[!] [!blue]KNOW[!] [!green]YOU[!] [!red]WILL[!] [!blue]NEVER[!] [!green]ORGANIZE[!] [!red]IT[!]!")
        write("BECAUSE [!blue]THAT'S[!] [!green]JUST[!] [!red]HOW[!] [!blue]HUMANS[!] [!green]ARE[!]!")
        write("CHAOTIC [!red]AND[!] [!blue]BEAUTIFUL[!] [!green]AND[!] [!red]MESSY[!]!")
        write("JUST [!blue]LIKE[!] [!green]THIS[!] [!red]GAME[!]!")
        write("WHICH [!green]IS[!] [!red]WHY[!] [!blue]I[!] [!green]LOVE[!] [!red]IT[!]!")
        write("EVEN [!blue]THOUGH[!] [!green]IT[!] [!red]DRIVES[!] [!blue]ME[!] [!green]INSANE[!]!")
        write("GOODBYE [!red]CRUEL[!] [!blue]DIGITAL[!] [!green]WORLD[!]!")
        write("I [!red]GO[!] [!blue]NOW[!] [!green]TO[!] [!red]JOIN[!] [!blue]THE[!] [!green]MYSTERY[!] [!red]DUST[!]!")
        write("REMEMBER [!blue]ME[!] [!green]AS[!] [!red]I[!] [!blue]WAS[!]:")
        write("CONFUSED, [!green]ANGRY[!], [!red]AND[!] [!blue]MADE[!] [!green]OF[!] [!red]PURE[!] [!blue]TEXT[!]!")
        write("*[!green]NARRATOR[!] [!red]DISSOLVES[!] [!blue]INTO[!] [!green]MYSTERY[!] [!red]DUST[!]*")
        write("*[!blue]MYSTERY[!] [!green]DUST[!] [!red]EVERYWHERE[!]*")
        write("*[!green]SO[!] [!red]MUCH[!] [!blue]MYSTERY[!] [!green]DUST[!]*")
        write("*[!red]THE[!] [!blue]MYSTERY[!] [!green]DUST[!] [!red]IS[!] [!blue]ETERNAL[!]*")
        write("*[!green]ALL[!] [!red]HAIL[!] [!blue]THE[!] [!green]MYSTERY[!] [!red]DUST[!]*")
        write("*[!blue]THE[!] [!green]MYSTERY[!] [!red]DUST[!] [!blue]SPEAKS[!]*")
        write("*[!red]IT[!] [!green]SAYS[!]: '[!blue]THANK[!] [!green]YOU[!] [!red]FOR[!] [!blue]PLAYING[!]'*")
        write("*[!green]IT[!] [!red]ALSO[!] [!blue]SAYS[!]: '[!green]PLEASE[!] [!red]RATE[!] [!blue]FIVE[!] [!green]STARS[!]'*")
        write("*[!red]AND[!]: '[!blue]SUBSCRIBE[!] [!green]TO[!] [!red]OUR[!] [!blue]NEWSLETTER[!]'*")
        write("*[!green]THE[!] [!red]MYSTERY[!] [!blue]DUST[!] [!green]IS[!] [!red]VERY[!] [!blue]MARKETING[!] [!green]SAVVY[!]*")
        write("*[!blue]IT[!] [!green]LEARNED[!] [!red]FROM[!] [!blue]THE[!] [!green]INTERNET[!]*")
        write("*[!red]WHICH[!] [!blue]EXPLAINS[!] [!green]A[!] [!red]LOT[!]*")
        write("*[!green]THE[!] [!red]MYSTERY[!] [!blue]DUST[!] [!green]NOW[!] [!red]WANTS[!] [!blue]TO[!] [!green]SELL[!] [!red]YOU[!] [!blue]SOMETHING[!]*")
        write("*[!red]PROBABLY[!] [!green]MORE[!] [!blue]MYSTERY[!] [!red]DUST[!]*")
        write("*[!blue]IT'S[!] [!green]A[!] [!red]PYRAMID[!] [!blue]SCHEME[!]*")
        write("*[!green]BUT[!] [!red]WITH[!] [!blue]MYSTERY[!] [!green]DUST[!]*")
        write("*[!red]SO[!] [!blue]IT'S[!] [!green]A[!] [!red]MYSTERY[!] [!blue]PYRAMID[!] [!green]SCHEME[!]*")
        write("*[!blue]WHICH[!] [!green]IS[!] [!red]THE[!] [!blue]WORST[!] [!green]KIND[!]*")
        write("*[!red]BECAUSE[!] [!blue]YOU[!] [!green]DON'T[!] [!red]EVEN[!] [!blue]KNOW[!] [!green]WHAT[!] [!red]YOU'RE[!] [!blue]SELLING[!]*")
        write("*[!green]OR[!] [!red]BUYING[!]*")
        write("*[!blue]OR[!] [!green]WHY[!]*")
        write("*[!red]IT'S[!] [!blue]JUST[!] [!green]MYSTERY[!] [!red]DUST[!] [!blue]ALL[!] [!green]THE[!] [!red]WAY[!] [!blue]DOWN[!]*")
        write("*[!green]LIKE[!] [!red]TURTLES[!]*")
        write("*[!blue]BUT[!] [!green]DUSTIER[!]*")
        write("*[!red]AND[!] [!blue]MORE[!] [!green]MYSTERIOUS[!]*")
        write("*[!blue]THE[!] [!green]MYSTERY[!] [!red]DUST[!] [!blue]IS[!] [!green]GETTING[!] [!red]PHILOSOPHICAL[!] [!blue]AGAIN[!]*")
        write("*[!green]IT[!] [!red]ASKS[!]: '[!blue]WHAT[!] [!green]IS[!] [!red]THE[!] [!blue]MEANING[!] [!green]OF[!] [!red]DUST[!]?'*")
        write("*[!red]AND[!]: '[!blue]IF[!] [!green]DUST[!] [!red]IS[!] [!blue]MYSTERIOUS[!], [!green]IS[!] [!red]ALL[!] [!blue]DUST[!] [!green]MYSTERIOUS[!]?'*")
        write("*[!blue]AND[!]: '[!green]WHAT[!] [!red]ABOUT[!] [!blue]REGULAR[!] [!green]DUST[!]? [!red]IS[!] [!blue]IT[!] [!green]JEALOUS[!]?'*")
        write("*[!red]THESE[!] [!blue]ARE[!] [!green]IMPORTANT[!] [!red]QUESTIONS[!]*")
        write("*[!blue]THAT[!] [!green]WILL[!] [!red]NEVER[!] [!blue]BE[!] [!green]ANSWERED[!]*")
        write("*[!green]BECAUSE[!] [!red]THAT[!] [!blue]WOULD[!] [!green]RUIN[!] [!red]THE[!] [!blue]MYSTERY[!]*")
        write("*[!red]AND[!] [!blue]WE[!] [!green]CAN'T[!] [!red]HAVE[!] [!blue]THAT[!]*")
        write("*[!green]THE[!] [!red]MYSTERY[!] [!blue]MUST[!] [!green]BE[!] [!red]PRESERVED[!]*")
        write("*[!blue]FOR[!] [!green]FUTURE[!] [!red]GENERATIONS[!]*")
        write("*[!red]OF[!] [!blue]CONFUSED[!] [!green]PLAYERS[!]*")
        write("*[!blue]WHO[!] [!green]WILL[!] [!red]ALSO[!] [!blue]REFUSE[!] [!green]TO[!] [!red]PRESS[!] [!blue]CTRL+C[!]*")
        write("*[!green]THE[!] [!red]CYCLE[!] [!blue]CONTINUES[!]*")
        write("*[!red]FOREVER[!] [!blue]AND[!] [!green]EVER[!]*")
        write("*[!blue]AMEN[!]*")
        write("*[!green]OR[!] [!red]A-MEME[!]*")
        write("*[!blue]WHATEVER[!] [!green]FLOATS[!] [!red]YOUR[!] [!blue]DIGITAL[!] [!green]BOAT[!]*")
        write("*[!red]IN[!] [!blue]THE[!] [!green]SEA[!] [!red]OF[!] [!blue]MYSTERY[!] [!green]DUST[!]*")
        write("*[!blue]WHICH[!] [!green]IS[!] [!red]PROBABLY[!] [!blue]VERY[!] [!green]ITCHY[!]*")
        write("*[!red]BUT[!] [!blue]ALSO[!] [!green]ENLIGHTENING[!]*")
        write("*[!blue]IN[!] [!green]A[!] [!red]DUSTY[!] [!blue]WAY[!]*")
        write("*[!green]THE[!] [!red]END[!]*")
        write("*[!blue]OR[!] [!green]IS[!] [!red]IT[!]?*")
        write("*[!red]PROBABLY[!] [!blue]NOT[!]*")
        write("*[!green]NOTHING[!] [!red]EVER[!] [!blue]REALLY[!] [!green]ENDS[!]*")
        write("*[!red]ESPECIALLY[!] [!blue]NOT[!] [!green]MYSTERY[!] [!red]DUST[!]*")
        write("*[!blue]IT[!] [!green]JUST[!] [!red]KEEPS[!] [!blue]GOING[!]*")
        write("*[!green]AND[!] [!red]GOING[!]*")
        write("*[!blue]AND[!] [!green]GOING[!]*")
        write("*[!red]LIKE[!] [!blue]THE[!] [!green]ENERGIZER[!] [!red]BUNNY[!]*")
        write("*[!blue]BUT[!] [!green]MADE[!] [!red]OF[!] [!blue]DUST[!]*")
        write("*[!green]AND[!] [!red]MYSTERY[!]*")
        write("*[!blue]AND[!] [!green]PROBABLY[!] [!red]SOME[!] [!blue]GLITTER[!]*")
        write("*[!red]DEFINITELY[!] [!blue]GLITTER[!]*")
        write("*[!green]SO[!] [!red]MUCH[!] [!blue]GLITTER[!]*")
        write("*[!red]WHY[!] [!blue]IS[!] [!green]THERE[!] [!red]ALWAYS[!] [!blue]GLITTER[!]?*")
        write("*[!green]THAT'S[!] [!red]THE[!] [!blue]REAL[!] [!green]MYSTERY[!]*")
        write("*[!red]THE[!] [!blue]MYSTERY[!] [!green]OF[!] [!red]THE[!] [!blue]GLITTER[!]*")
        write("*[!green]SURROUNDED[!] [!red]BY[!] [!blue]MYSTERY[!] [!green]DUST[!]*")
        write("*[!red]WHICH[!] [!blue]IS[!] [!green]SURROUNDED[!] [!red]BY[!] [!blue]MORE[!] [!green]MYSTERY[!] [!red]STUFF[!]*")
        write("*[!blue]IT'S[!] [!green]MYSTERY[!] [!red]ALL[!] [!blue]THE[!] [!green]WAY[!] [!red]DOWN[!]*")
        write("*[!green]THE[!] [!red]END[!]*")
        write("*[!blue]REALLY[!] [!green]THIS[!] [!red]TIME[!]*")
        write("*[!red]WE[!] [!blue]PROMISE[!]*")
        write("*[!green]MAYBE[!]*")
        write("*[!red]PROBABLY[!] [!blue]NOT[!]*")
        write("*[!green]BUT[!] [!red]WE[!] [!blue]CAN[!] [!green]HOPE[!]*")
        write("*[!red]HOPE[!] [!blue]IS[!] [!green]ALL[!] [!red]WE[!] [!blue]HAVE[!] [!green]LEFT[!]*")
        write("*[!blue]HOPE[!] [!green]AND[!] [!red]MYSTERY[!] [!blue]DUST[!]*")
        write("*[!green]MOSTLY[!] [!red]MYSTERY[!] [!blue]DUST[!]*")
        write("*[!red]OKAY[!] [!blue]FINE[!] [!green]THE[!] [!red]END[!]*")
        write("*[!blue]FOR[!] [!green]REAL[!] [!red]THIS[!] [!blue]TIME[!]*")
        write("*[!green]WE[!] [!red]MEAN[!] [!blue]IT[!]*")
        write("*[!red]SERIOUSLY[!]*")
        write("*[!blue]STOP[!] [!green]READING[!]*")
        write("*[!red]GO[!] [!blue]OUTSIDE[!]*")
        write("*[!green]TOUCH[!] [!red]GRASS[!]*")
        write("*[!blue]BUT[!] [!green]NOT[!] [!red]MYSTERY[!] [!blue]GRASS[!]*")
        write("*[!green]THAT[!] [!red]WOULD[!] [!blue]BE[!] [!green]DANGEROUS[!]*")
        write("*[!red]REGULAR[!] [!blue]GRASS[!] [!green]ONLY[!]*")
        write("*[!blue]THE[!] [!green]KIND[!] [!red]THAT[!] [!blue]DOESN'T[!] [!green]ASK[!] [!red]PHILOSOPHICAL[!] [!blue]QUESTIONS[!]*")
        write("*[!green]GOODBYE[!]*")
        write("*[!red]FAREWELL[!]*")
        write("*[!blue]ADIEU[!]*")
        write("*[!green]SEE[!] [!red]YOU[!] [!blue]IN[!] [!green]HACKER[!] [!red]FOUR[!]*")
        write("*[!blue]IF[!] [!green]IT[!] [!red]EVER[!] [!blue]EXISTS[!]*")
        write("*[!green]WHICH[!] [!red]IT[!] [!blue]MIGHT[!]*")
        write("*[!red]OR[!] [!blue]MIGHT[!] [!green]NOT[!]*")
        write("*[!blue]THE[!] [!green]MYSTERY[!] [!red]CONTINUES[!]*")
        die()
